### PR TITLE
Preparing Jumping animation

### PR DESCRIPTION
**Pull request by DeRobyJ**
I thought that jumping still wasn't really natural.
So I just reused the walking animation to make the character look like it's jumping.

It needs a new frame, but I think it's fine for now.

(it's three commits because for some reason the main scene changed the order of audio files)

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Rebase?

**Comment by DeRobyJ** [comment]
Sorry?
I just forked and cloned the project

**Comment by akien-mga** [comment]
He means that you should squash your three commits into one, as the last two of them just add unnecessary noise to the git history (click on them to see the diffs).

**Comment by DeRobyJ** [comment]
Oh I see.
Ok, I'll figure it out after having upgraded my Tiled

**Pull request closed without merging**
