### PR TITLE
jump animation preparation

### PR DESCRIPTION
**Pull request by DeRobyJ**
Rebased #10

### CODE REVIEW

**Comment by ObaniGemini** [comment]
Will you make an animation for that ?

**Comment by DeRobyJ** [comment]
I'm sorry, I'm not good at drawing or pixel art.
For now, the walking "step" frame is used, which looks ok to me, but it needs a proper one.

**Comment by ObaniGemini** [comment]
I think it will be good enough for now. Should we merge it @alketii @bojidar-bg ?

**Comment by alketii** [comment]
There is a jumping frame here https://lut.im/LStGJaIFey/e1KfuaZrlP0nO757.png , for other graphics you can see http://www.widgetworx.com/spritelib/

**Comment by DeRobyJ** [comment]
Should I put the new step and open a new pull request?

**Comment by ObaniGemini** [comment]
There isn't enough done here for I merge this PR. An animation without its medias is meaningless, and this alogrithmic adds are to be made within 5 seconds

**Pull request closed without merging**
